# Generated by Django 4.2 on 2025-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='testimonials/profile_images/')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('trustpilot_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
