# Generated by Django 4.2 on 2025-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment_price', models.CharField(blank=True, max_length=50, null=True)),
                ('style_name', models.CharField(blank=True, max_length=100, null=True)),
                ('style_file', models.FileField(blank=True, null=True, upload_to='style_files/')),
                ('delivery_date', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_slides', models.IntegerField(default=1)),
                ('delivery_option', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_option_price', models.FloatField(default=0)),
                ('estimated_price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('google_checkbox', models.BooleanField(default=False)),
                ('google_link', models.TextField(blank=True, null=True)),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='presentations/')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
