# Generated by Django 4.2 on 2025-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('brandingTemplates', 'Branding Templates'), ('brochure', 'Brochure'), ('businessPresentation', 'Business Presentation'), ('companyProfile', 'Company Profile'), ('flyer', 'Flyer'), ('graphicDesign', 'Graphic Design'), ('pitchDeckDesign', 'Pitch Deck Design'), ('powerpoint', 'PowerPoint'), ('salesDesign', 'Sales Design')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
